const UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,OPTIONS'};
const cats=[['法院/判决',['法院','裁判','判决','民初','民终','案号','诉讼','开庭']],['执行风险',['执行','被执行人','限制高消费','失信','终本']],['政府/监管',['政府','市场监督','行政处罚','信用中国','公示','监管']],['工商线索',['企业信用','法定代表人','股东','统一社会信用代码','工商','成立日期']],['新闻/官网',['新闻','官网','公告','采访','活动','报道']],['人物/职业',['董事','经理','创始人','CEO','员工','任职','校长','负责人']]];
function catOf(t){for(const [c,ks] of cats)if(ks.some(k=>t.includes(k)))return c;return '其他公开资料'}
function strip(s=''){return s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
function domain(u){try{return new URL(u).hostname.replace(/^www\./,'')}catch{return ''}}
function compact(s=''){return s.toLowerCase().replace(/[\s\-—_·•（）()【】\[\]“”"'，,。.:：;；/\\]/g,'')}
function authority(url){const d=domain(url);if(/(^|\.)gov\.cn$|court\.gov\.cn$|samr\.gov\.cn$|creditchina\.gov\.cn$|sse\.com\.cn$|szse\.cn$/.test(d))return ['一级','高'];if(/people\.com\.cn$|xinhuanet\.com$|thepaper\.cn$|caixin\.com$|21jingji\.com$|chinanews\.com\.cn$|gmw\.cn$|whb\.cn$/.test(d))return ['二级','中高'];if(/qcc\.com$|tianyancha\.com$|aiqicha\.baidu\.com$|企查查|天眼查/.test(d))return ['二级','中高'];return ['三级','中']}
function coreNames(q){const raw=compact(q);const names=new Set([raw]);let short=raw.replace(/^(上海|北京|广州|深圳|杭州|南京|成都|武汉|重庆|天津|苏州|西安)/,'').replace(/(有限责任公司|股份有限公司|有限公司|集团公司|集团|企业管理咨询|企业管理|管理咨询|教育科技|科技|咨询|公司)$/g,'');if(short.length>=2)names.add(short);for(const p0 of q.split(/[\s,，]+/)){const p=compact(p0);if(p.length>=2)names.add(p)}return [...names].filter(x=>x.length>=2)}
function score(q,r){const hay=compact(`${r.title} ${r.snippet}`), names=coreNames(q);let s=0;if(hay.includes(compact(q)))s+=12;for(const n of names)if(n.length>=2&&hay.includes(n))s+=Math.min(8,n.length);const d=domain(r.url);if(/gov\.cn$|court\.gov\.cn$/.test(d))s+=8;if(/qcc\.com$|tianyancha\.com$|aiqicha\.baidu\.com$/.test(d))s+=5;if(/[法院判决执行失信处罚法定代表人股东]/.test(`${r.title}${r.snippet}`))s+=2;return s}
function extractDate(s){const m=s.match(/(20\d{2})[-年/.](0?[1-9]|1[0-2])[-月/.](0?[1-9]|[12]\d|3[01])/);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`:''}
function unwrap(u){try{const x=new URL(u);for(const k of ['url','target','u','uddg']){const v=x.searchParams.get(k);if(v&&/^https?:/i.test(decodeURIComponent(v)))return decodeURIComponent(v)}}catch{}return u}
async function fetchText(url){const r=await fetch(url,{headers:{'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9'}});if(!r.ok)throw new Error(String(r.status));return await r.text()}
function parseGeneric(h,engine){const out=[];let re;if(engine==='360')re=/<h3[^>]*>[\s\S]*?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?(?:<p[^>]*class=["'][^"']*(?:res-desc|summary|content)[^"']*["'][^>]*>([\s\S]*?)<\/p>)?/gi;else if(engine==='sogou')re=/<h3[^>]*>[\s\S]*?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?(?:<p[^>]*class=["'][^"']*(?:str_info|txt-info)[^"']*["'][^>]*>([\s\S]*?)<\/p>)?/gi;else if(engine==='baidu')re=/<h3[^>]*class=["'][^"']*t[^"']*["'][^>]*>[\s\S]*?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?(?:<span[^>]*class=["'][^"']*(?:content-right_8Zs40|c-font-normal)[^"']*["'][^>]*>([\s\S]*?)<\/span>)?/gi;else return out;for(const m of h.matchAll(re)){const title=strip(m[2]);if(title)out.push({url:unwrap(m[1]),title,snippet:strip(m[3]||''),engine})}return out.slice(0,10)}
async function engineSearch(engine,q){try{let u='';if(engine==='360')u='https://m.so.com/s?q='+encodeURIComponent(q);if(engine==='sogou')u='https://www.sogou.com/web?query='+encodeURIComponent(q);if(engine==='baidu')u='https://www.baidu.com/s?wd='+encodeURIComponent(q);const h=await fetchText(u);return parseGeneric(h,engine)}catch{return []}}
async function bing(q){try{const x=await fetchText('https://www.bing.com/search?format=rss&count=10&setlang=zh-hans&q='+encodeURIComponent(q));const out=[];for(const m of x.matchAll(/<item>([\s\S]*?)<\/item>/gi)){const z=m[1],g=t=>{const a=z.match(new RegExp(`<${t}>([\\s\\S]*?)<\\/${t}>`,'i'));return a?strip(a[1].replace(/<!\[CDATA\[|\]\]>/g,'')):''};out.push({title:g('title'),url:g('link'),snippet:g('description'),engine:'bing-cn'})}return out}catch{return []}}
function buildQueries(q){return [`"${q}"`,`"${q}" 法定代表人 股东`,`"${q}" 法院 判决 执行`,`"${q}" 行政处罚 信用中国`,`"${q}" 新闻 活动 任职`]}
function entityType(q){if(/公司|集团|企业|中心|事务所|学校|医院|银行|科技|教育|咨询/.test(q))return '公司/机构';if(/[（(]20\d{2}[）)].*民/.test(q))return '案号';if(q.trim().split(/\s+/).length<=3&&q.length<=12)return '人物/短名称';return '待确认'}
export default {async fetch(req){if(req.method==='OPTIONS')return new Response('',{headers:CORS});const url=new URL(req.url);if(url.pathname==='/health')return Response.json({ok:true,version:'2.0-cn',engines:['360','搜狗','百度','必应中文'],free_mode:true},{headers:CORS});if(url.pathname!=='/api/search')return new Response('Not found',{status:404,headers:CORS});const q=(url.searchParams.get('q')||'').trim();if(!q)return Response.json({error:'missing q'},{status:400,headers:CORS});const queries=buildQueries(q);const jobs=[];for(const query of queries){jobs.push(engineSearch('360',query),engineSearch('sogou',query),engineSearch('baidu',query),bing(query))}const batches=await Promise.all(jobs), seen=new Set(), results=[];for(const arr of batches)for(const r of arr){const u=unwrap(r.url);if(!u||seen.has(u))continue;seen.add(u);const sc=score(q,{...r,url:u});if(sc<5)continue;const text=`${r.title} ${r.snippet}`,[a,c]=authority(u);results.push({title:r.title||u,url:u,snippet:r.snippet||'',domain:domain(u),engine:r.engine,category:catOf(text),authority:a,confidence:c,date:extractDate(text),relevance_score:sc})}results.sort((a,b)=>b.relevance_score-a.relevance_score||({一级:3,二级:2,三级:1}[b.authority]-({一级:3,二级:2,三级:1}[a.authority]));const final=results.slice(0,50),counts={};for(const r of final)counts[r.category]=(counts[r.category]||0)+1;const engines={};for(const r of final)engines[r.engine]=(engines[r.engine]||0)+1;const timeline=final.filter(r=>r.date).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,20).map(r=>({date:r.date,title:r.title,url:r.url}));return Response.json({query:q,entity_type:entityType(q),queries,engines,counts,results:final,timeline,generated_at:new Date().toISOString(),version:'2.0-cn',note:final.length?'中文优先多引擎检索；结果按名称相关度与来源权威性排序。':'中文搜索源没有返回达到相关性阈值的公开结果；不使用无关结果填充。'},{headers:{...CORS,'Cache-Control':'public, max-age=90'}})}};