const UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,OPTIONS'};
const BAD=/cn-kr\.net|kr-cn\.com|maigoo\.com|99114\.com|yellowurl\.cn|b2b168\.com|huangye88\.com|gongchang\.com/i;
const JUNK=/招聘|采购|供应|批发|招商|加盟|下载|小说|游戏|天气|商品|企业名录|黄页大全|公司大全|厂家|报价|商机/i;
const JUD=/法院|裁判|判决|裁定|调解书|民初|民终|刑初|刑终|行初|行终|案号|诉讼|原告|被告|上诉人|合同纠纷|服务合同纠纷/;
const EXEC=/执行|被执行人|限制高消费|失信被执行人|终本|执行标的|执恢|执异|执保/;
const REG=/行政处罚|市场监督|信用中国|监管|处罚决定|经营异常/;
const BIZ=/法定代表人|股东|统一社会信用代码|注册资本|工商|董事|经理|监事|变更/;
function strip(s=''){return s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
function dom(u){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,'')}catch{return ''}}
function compact(s=''){return s.toLowerCase().replace(/[\s\-—_·•（）()【】\[\]“”"'，,。.:：;；/\\]/g,'')}
function short(q){return compact(q).replace(/^(上海|北京|广州|深圳|杭州|南京|成都|武汉|重庆|天津|苏州|西安)/,'').replace(/(有限责任公司|股份有限公司|有限公司|集团公司|集团|企业管理咨询|企业管理|管理咨询|教育科技|科技|咨询|公司)$/g,'')}
function match(q,t){const h=compact(t),f=compact(q),s=short(q);return h.includes(f)||(s.length>=4&&h.includes(s))}
function dateOf(s){const m=s.match(/(20\d{2})[-年/.](0?[1-9]|1[0-2])[-月/.](0?[1-9]|[12]\d|3[01])/);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`:''}
function caseOf(s){const m=s.match(/[（(](20\d{2})[）)][^，。\s]{1,20}(?:民|刑|行|执|赔|破)[^，。\s]{0,15}\d+号/);return m?m[0]:''}
async function text(url){const r=await fetch(url,{headers:{'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9'}});if(!r.ok)throw Error(String(r.status));return r.text()}
function unwrap(u){try{const x=new URL(u);for(const k of ['url','target','u','uddg']){const v=x.searchParams.get(k);if(v){const z=decodeURIComponent(v);if(/^https?:/i.test(z))return z}}}catch{}return u}
async function bing(q,source='bing-cn'){try{const x=await text('https://www.bing.com/search?format=rss&count=20&setlang=zh-hans&mkt=zh-CN&q='+encodeURIComponent(q)),a=[];for(const m of x.matchAll(/<item>([\s\S]*?)<\/item>/gi)){const z=m[1],g=t=>{const v=z.match(new RegExp(`<${t}>([\\s\\S]*?)<\\/${t}>`,'i'));return v?strip(v[1].replace(/<!\[CDATA\[|\]\]>/g,'')):''};a.push({title:g('title'),url:g('link'),snippet:g('description'),source})}return a}catch{return []}}
async function baidu(q){try{const h=await text('https://www.baidu.com/s?ie=utf-8&rn=20&wd='+encodeURIComponent(q)),a=[];for(const m of h.matchAll(/<h3[^>]*>[\s\S]*?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const title=strip(m[2]);if(title)a.push({title,url:unwrap(m[1]),snippet:'',source:'baidu'})}return a}catch{return []}}
async function mediawiki(q){try{const api='https://zh.wikisource.org/w/api.php?action=query&generator=search&gsrnamespace=0&gsrlimit=20&gsrsearch='+encodeURIComponent('"'+q+'"')+'&prop=extracts&exintro=1&explaintext=1&exchars=500&format=json&origin=*';const r=await fetch(api,{headers:{'User-Agent':UA}});if(!r.ok)throw Error(String(r.status));const j=await r.json(),pages=Object.values(j.query?.pages||{});return pages.map(p=>({title:p.title,url:'https://zh.wikisource.org/wiki/'+encodeURIComponent(p.title.replace(/ /g,'_')),snippet:p.extract||'',source:'wikisource-api'}))}catch{return []}}
async function directCourt(q){const qs=[`site:wenshu.court.gov.cn "${q}"`,`site:cjdh.court.gov.cn "${q}" 裁判`,`site:court.gov.cn "${q}" 判决 裁定`,`site:rmfygg.court.gov.cn "${q}"`];return (await Promise.all(qs.map(x=>bing(x,'court-index')))).flat()}
async function directExecution(q){const qs=[`site:zxgk.court.gov.cn "${q}" 被执行人`,`site:court.gov.cn "${q}" 失信 被执行人 执行`];return (await Promise.all(qs.map(x=>bing(x,'execution-index')))).flat()}
function classify(t,u,source){const d=dom(u);if(source==='wikisource-api'||JUD.test(t)||/wenshu\.court\.gov\.cn|cjdh\.court\.gov\.cn|rmfygg\.court\.gov\.cn/.test(d))return '司法/裁判';if(EXEC.test(t)||/zxgk\.court\.gov\.cn/.test(d))return '执行/失信';if(REG.test(t))return '监管/处罚';if(BIZ.test(t))return '工商/任职';return '新闻/官网'}
function rank(u,source){const d=dom(u);if(/court\.gov\.cn$|gov\.cn$/.test(d))return 5;if(source==='wikisource-api'||/wikisource\.org$/.test(d))return 4;if(/qcc\.com$|tianyancha\.com$|aiqicha\.baidu\.com$/.test(d))return 4;if(/people\.com\.cn$|xinhuanet\.com$|thepaper\.cn$|caixin\.com$|whb\.cn$/.test(d))return 4;return 1}
function make(q,r){const u=unwrap(r.url||'');if(!u||BAD.test(dom(u)))return null;const all=`${r.title||''} ${r.snippet||''}`;if(!match(q,all))return null;if(JUNK.test(all)&&rank(u,r.source)<=1)return null;const category=classify(all,u,r.source),rk=rank(u,r.source);if(rk<=1&&category==='新闻/官网'&&!/新闻|公告|采访|活动|官网/.test(all))return null;let score=(compact(all).includes(compact(q))?50:30)+rk*10+(category==='司法/裁判'?25:category==='执行/失信'?20:0);return {title:r.title||u,url:u,snippet:r.snippet||'',domain:dom(u),engine:r.source,source_type:rk===5?'法院/政府官方':r.source==='wikisource-api'?'裁判文书公开存档':rk===4?'高价值公开来源':'其他公开网页',authority:rk===5?'一级':rk===4?'二级':'三级',evidence_state:rk===5?'官方原文/官方索引':r.source==='wikisource-api'?'裁判文书公开存档，建议与官方记录交叉核验':'公开线索',category,date:dateOf(all),case_no:caseOf(all),score}}
async function general(q){const queries=[`"${q}" 法定代表人 股东 变更`,`"${q}" 行政处罚 信用中国`,`"${q}" 新闻 公告`,`"${q}"`];const jobs=[];for(const x of queries){jobs.push(bing(x));jobs.push(baidu(x))}return (await Promise.all(jobs)).flat()}
function unique(rows){const seen=new Set(),out=[];for(const r of rows.sort((a,b)=>b.score-a.score)){const k=compact((r.case_no||'')+' '+r.title);if(seen.has(k))continue;seen.add(k);out.push(r)}return out}
export default {async fetch(req){if(req.method==='OPTIONS')return new Response('',{headers:CORS});const u=new URL(req.url);if(u.pathname==='/health')return Response.json({ok:true,version:'6.0-direct-sources',free_mode:true,data_sources:['中国裁判文书网官方索引','最高人民法院/场景导航索引','中国执行信息公开网索引','维基文库裁判文书公开存档 API','百度','必应中文']},{headers:CORS});if(u.pathname!=='/api/search')return new Response('Not found',{status:404,headers:CORS});const q=(u.searchParams.get('q')||'').trim();if(!q)return Response.json({error:'missing q'},{status:400,headers:CORS});const settled=await Promise.allSettled([mediawiki(q),directCourt(q),directExecution(q),general(q)]);const names=['维基文库裁判文书API','法院官方索引','执行官方索引','综合中文检索'];const source_status={};let raw=[];settled.forEach((x,i)=>{if(x.status==='fulfilled'){source_status[names[i]]={ok:true,returned:x.value.length};raw.push(...x.value)}else source_status[names[i]]={ok:false,returned:0}});let rows=unique(raw.map(x=>make(q,x)).filter(Boolean));const judicial=rows.filter(x=>x.category==='司法/裁判').slice(0,20),enforcement=rows.filter(x=>x.category==='执行/失信').slice(0,15),regulatory=rows.filter(x=>x.category==='监管/处罚').slice(0,12),business=rows.filter(x=>x.category==='工商/任职').slice(0,12),news=rows.filter(x=>x.category==='新闻/官网').slice(0,12);const timeline=rows.filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,30).map(x=>({date:x.date,title:x.title,category:x.category,case_no:x.case_no,url:x.url}));return Response.json({query:q,version:'6.0-direct-sources',entity_type:/公司|集团|企业|中心|科技|咨询|教育/.test(q)?'公司/机构':'人物/其他',source_status,judicial_results:judicial,enforcement_results:enforcement,regulatory_results:regulatory,business_results:business,news_results:news,other_results:[],timeline,note:`司法 ${judicial.length} · 执行 ${enforcement.length} · 监管 ${regulatory.length}。V6 已加入独立司法数据源，不再只依赖普通搜索结果。`,limitations:'裁判文书网和执行信息公开网可能存在登录、验证码、动态接口或反自动化限制；系统不会绕过这些限制。官方索引不可机器读取时，会明确显示数据源状态，并用公开裁判文书存档补充发现能力。'},{headers:{...CORS,'Cache-Control':'public, max-age=60'}})}};